import { CompetitionInterface } from "../types/index";
import { Request, Response } from "express";

const mockCompetitions: CompetitionInterface[] = [
    {
        id: 1,
        owner: "alice_dev",
        title: "Spring UI Challenge",
        description: "Design a responsive dashboard UI using only CSS and HTML.",
        themes: ["UI", "CSS", "Frontend"],
        submissionTimeLimit: 72,
        votingTimeLimit: 48,
        startDate: "2026-03-01T00:00:00Z",
        endDate: "2026-03-10T00:00:00Z",
        phase: "ended",
        participantCount: 34,
        submissions: [],
        totalVoteCount: 128,
    },
    {
        id: 2,
        owner: "bob_creates",
        title: "AI Prompt Art Fest",
        description: "Generate the most creative artwork using AI prompts.",
        themes: ["AI", "Art", "Creativity"],
        submissionTimeLimit: 48,
        votingTimeLimit: 24,
        startDate: "2026-04-01T00:00:00Z",
        endDate: "2026-04-15T00:00:00Z",
        phase: "voting",
        participantCount: 61,
        submissions: [],
        totalVoteCount: 305,
    },
    {
        id: 3,
        owner: "carol_codes",
        title: "Hackathon: Climate Tech",
        description: "Build a tool that addresses a climate change problem.",
        themes: ["Climate", "Sustainability", "Tech"],
        submissionTimeLimit: 96,
        votingTimeLimit: 72,
        startDate: "2026-04-10T00:00:00Z",
        endDate: "2026-04-20T00:00:00Z",
        phase: "submission",
        participantCount: 22,
        submissions: [],
        totalVoteCount: 0,
    },
    {
        id: 4,
        owner: "dan_designs",
        title: "Logo Design Blitz",
        description: "Create a logo for a fictional startup in under an hour.",
        themes: ["Design", "Branding", "Logo"],
        submissionTimeLimit: 1,
        votingTimeLimit: 24,
        startDate: "2026-02-14T00:00:00Z",
        endDate: "2026-02-16T00:00:00Z",
        phase: "ended",
        participantCount: 19,
        submissions: [],
        totalVoteCount: 87,
    },
    {
        id: 5,
        owner: "eve_builds",
        title: "Open Source Sprint",
        description: "Contribute a meaningful feature to any open source project.",
        themes: ["Open Source", "Collaboration", "Code"],
        submissionTimeLimit: 120,
        votingTimeLimit: 48,
        startDate: "2026-04-12T00:00:00Z",
        endDate: "2026-04-30T00:00:00Z",
        phase: "submission",
        participantCount: 45,
        submissions: [],
        totalVoteCount: 0,
    },
];

export function getAllCompetitions(req: Request, res: Response) {
    return
}
